In [39]:
import numpy as np
M = np.array([[0, 1, 1], [sqrt(2), 2, 0], [0, 1, 1]])

# set numpy printing options
np.set_printoptions(suppress=True)
np.set_printoptions(precision=3)

print ("--- FULL ---")
U, s, VT = np.linalg.svd(M, full_matrices=True)

print ("U:\n {}".format(U))
print ("s:\n {}".format(s))
print ("VT:\n {}".format(VT))

print ("--- REDUCED ---")

U, s, VT = np.linalg.svd(M, full_matrices=False)

print ("U:\n {}".format(U))
print ("s:\n {}".format(s))
print ("VT:\n {}".format(VT))

--- FULL ---
U:
 [[-0.408  0.577 -0.707]
 [-0.816 -0.577  0.   ]
 [-0.408  0.577  0.707]]
s:
 [2.828 1.414 0.   ]
VT:
 [[-0.408 -0.866 -0.289]
 [-0.577 -0.     0.816]
 [-0.707  0.5   -0.5  ]]
--- REDUCED ---
U:
 [[-0.408  0.577 -0.707]
 [-0.816 -0.577  0.   ]
 [-0.408  0.577  0.707]]
s:
 [2.828 1.414 0.   ]
VT:
 [[-0.408 -0.866 -0.289]
 [-0.577 -0.     0.816]
 [-0.707  0.5   -0.5  ]]


In [22]:
import numpy as np
import pandas as pd
from math import sqrt
import scipy
from scipy import linalg

In [60]:
def SVD(M):
    print("M - matrix\n")
    print(M)
    
    Mt = M.transpose()
    MdMt = M.dot(Mt)
    MtdM = Mt.dot(M)            
    λ, V = linalg.eig(MtdM)
    
    print("\nλ - eigenvalue\n")
    print(λ)
    print("\n-------------\n")
    
    Vt = V.transpose()
    
    for i in range(len(λ)):
        λ[i] = sqrt(abs(λ[i]))
        
    λ = sorted(λ, reverse = True)
    
    S = np.diag(λ)
    S_inversed = np.linalg.inv(S)
    
    print("Vt - V transposed\n")
    for i in range(len(V)):
        print(V[:,i])
        
    U = M.dot(V.dot(S_inversed))    
    
#     u, s, vt = np.linalg.svd(a, full_matrices=False)
    print ("\n--- FULL ---\n")
    
    print("U\n")
    print(U)
    print("S\n")
    print(S)
    print("V\n")
    print(V)
    
#     print ("\n--- REDUCED ---\n")
    
#     print(u)
#     print("\n-------------")
#     print(s)
#     print("\n-------------")
#     print(vt)         
#     print("\n-------------")
    
#     print("\n-------------")
#     print(M)
#     print("\n-------------")
#     print(U.dot(S.dot(Vt)))

In [61]:
M = np.array([[0, 1, 1], [sqrt(2), 2, 0], [0, 1, 1]])
SVD(M)

M - matrix

[[0.    1.    1.   ]
 [1.414 2.    0.   ]
 [0.    1.    1.   ]]

λ - eigenvalue

[ 8.+0.j -0.+0.j  2.+0.j]

-------------

Vt - V transposed

[-0.408 -0.866 -0.289]
[ 0.707 -0.5    0.5  ]
[-0.577 -0.     0.816]

--- FULL ---

U

[[-4.082e-01+0.j -5.551e-17+0.j  2.946e+08+0.j]
 [-8.165e-01+0.j  1.110e-16+0.j -2.946e+08+0.j]
 [-4.082e-01+0.j -5.551e-17+0.j  2.946e+08+0.j]]
S

[[2.828+0.j 0.   +0.j 0.   +0.j]
 [0.   +0.j 1.414+0.j 0.   +0.j]
 [0.   +0.j 0.   +0.j 0.   +0.j]]
V

[[-0.408  0.707 -0.577]
 [-0.866 -0.5   -0.   ]
 [-0.289  0.5    0.816]]
